version: '3.12'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: portal_pln
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: django:latest
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: 10.10.11.19
      DB_NAME: portal_pln
      DB_USER: root
      DB_PASSWORD: ""
    depends_on:
      - db

volumes:
  db_data:
