services:
  db:
    image: mariadb:latest
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: portal_pln
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: portal_pln
      DATABASE_USER: root
      DATABASE_PASSWORD: ''

volumes:
  db_data:
