version: '3.12'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: portal_pln
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: portal_pln
      DATABASE_USER: root
      DATABASE_PASSWORD: ''

volumes:
  db_data:
