# Generated by Django 5.1.1 on 2024-10-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_date',
            field=models.CharField(default='Unknown Date', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
