# Generated by Django 5.1.1 on 2024-10-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_article_post_date_alter_article_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
