# Generated by Django 5.1.1 on 2024-10-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_lelang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lelang',
            name='hps',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lelang',
            name='instansi',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lelang',
            name='kode_lelang',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lelang',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lelang',
            name='nama_paket',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lelang',
            name='tahapan',
            field=models.CharField(max_length=500),
        ),
    ]
